### ISSUE TITLE
result value type is wrong

### ISSUE THREAD

**Issue by peaksnail** [apla/node-clickhouse#51]
hi

when the result include Int type, the value will be string but not number

any options to handle it?

thanks

**Comment by nezed** [comment]
This is a usual behavior for [U]Int64 in any case for any DBMS. This happens because JS had only Number (Float64) type, which has only 53 significand precision bits. 

For now you must convert numbers by yourself. I recommend you to use the new ES feature [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). 

I think it will be great to add BigInt conditional support into client itself, so PR welcome
