### ISSUE TITLE
How to inserts of array of javascript objects?

### ISSUE THREAD

**Issue by suenot** [apla/node-clickhouse#53]
In documentation there is only section "Insert single row of data:".

**Comment by nezed** [comment]
[Bulk data loading](https://github.com/apla/node-clickhouse/blob/master/README.md#bulk-data-loading-with-insert-statements) section should help

**Comment by suenot** [comment]
I write a simple example, but I'm not sure, that this solution is the best:
```js
const ClickHouse = require('@apla/clickhouse')
const ch = new ClickHouse(options)

var counter = 0

const sleep = (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms))
}

const main = async function() {
  while (true) {
    const writableStream = ch.query(`INSERT INTO tutorial.some`, (err) => {
      // console.log(err)
      console.log(`Insert complete, ${counter}! ${new Date()}`)
    })

    for(var i=0; i<500000; i++) {
      await writableStream.write(['2000-01-07', counter, 'some'])
      counter += 1
    }
    await writableStream.end()
    await sleep(1)
  }
}

main()
```

**Comment by nezed** [comment]
Its ok to use synchronous loops for small amount of data, so the second example looks like exactly what you need. (You may also find useful `for .. of` loop). 

You don't need to worry about sync or async nature of your `stream.write` because its better to have async data source and pipe it into writable stream. ([Example](https://github.com/apla/node-clickhouse/blob/master/README.md#inserting-large-dataset)). 

PS. Don’t forget to specify callback `ch.query` or `end` together with `error` stream event handlers. 
PS2. You’ve passing 1 to `sleep` fn when you need a 1000

**Comment by suenot** [comment]
Thanks, @nezed. You really help me solve my problem.
