### ISSUE TITLE
Error: Cannot read from istream at offset 0

### ISSUE THREAD

**Issue by vladimirteddy** [apla/node-clickhouse#62]
I query with format INSERT INTO MY_TABLE with option JSONEachRow, my data have one billion records, I splice and write up 1000 each time, and write from record 79k I have a bug Error: Cannot read from istream at offset 0.
My query `"INSERT INTO " + table + " FORMAT JSONEachRow " + data`.

![logs](https://user-images.githubusercontent.com/29521357/82631796-9cb1b580-9c20-11ea-97fa-b66fa31f57a5.png)
Log error on the server.

Please help my issue, thank.

**Comment by nezed** [comment]
@banbedangki Please provide more detailed example illustrating the way you are working with data

**Comment by banbedangki** [comment]
> @banbedangki Please provide more detailed example illustrating the way you are working with data

I use `ch.query("INSERT INTO " + table + " FORMAT JSONEachRow " + data).` My data is JSON arrays.

**Comment by banbedangki** [comment]
I POST with format 
`ch.query("INSERT INTO " + table + " FORMAT JSONEachRow " + data)`
 If I cancel command run code on terminal then data will be created. Can tell me why?
I think my bugs from here. When I POST one billion records, I split and POST ten thousand at a time but every POST 10k records, data not created on ClickHouse, if I cancel run code on the terminal then data will be created.

**Comment by banbedangki** [comment]
`let stream = ch.query("INSERT INTO " + table + " FORMAT JSONEachRow " + data)`. I'm log stream:
![screenshot_1](https://user-images.githubusercontent.com/29521357/82789529-a5122680-9e94-11ea-89c8-f351e45a3217.png)
What is '\n' in my query?

**Comment by vladimirteddy** [comment]
I'm fixed, thank for your interest.

**Comment by nezed** [comment]
@vladimirteddy It's a good news!

For now i can only suggest that the problem was caused by malformed query.
Also this driver is using [http interface](https://clickhouse.tech/docs/en/interfaces/http/) and always automatically adding `"\n"` after query to separate it from data, but it should not be a problem if you are using this driver as described in docs.

This means that you must choose one of following options:
- Use only one allowed in query format - [Values](https://clickhouse.tech/docs/en/interfaces/formats/#data-format-values)
- Write you data to returned Duplex(Writable)Stream and it will be properly sent in request body after query and without newline before End of File ([example](https://github.com/apla/node-clickhouse/blob/master/README.md#insert-single-row-of-data))

**Comment by nezed** [comment]
See also https://clickhouse.tech/docs/en/sql-reference/statements/insert-into/
